set exrc
set secure

set number


set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

set hlsearch
set incsearch

set ignorecase 
set smartcase

set autoindent


syntax on
colorscheme desert

set titlestring=%t
set title
" color evening
" set background=dark
" https://linuxhint.com/important_vim_settings/

" PLUGIN(s) :PlugInstall -> :PlugUpdate -> Remove..[<dd line && :PlugClean>]
call plug#begin('~/.vim/plugged')

"repo
Plug 'maksimr/vim-jsbeautify' 

"ex
"run only when called
"Plug 'repo/name' , { 'on': 'NameToggle' }

"run only 'for'
"Plug 'repo/name' , { 'for': 'markdown' }

"pull only on 'branch' <name-branch>
"Plug 'repo/name' , { 'branch': '<name-branch>' }

"build correctly -> 'do' [run a command after install] <cmake>
"Plug 'repo/name' , { 'do': 'make <name-plug>' }


call plug#end()








