set exrc
set secure

set number


set tabstop=4
set softtabstop=4
set shiftwidth=4
set noexpandtab

set hlsearch
set incsearch

set ignorecase 
set smartcase

set autoindent


syntax on
colorscheme desert

set titlestring=%t
set title
" color evening
" set background=dark
" https://linuxhint.com/important_vim_settings/
